### PR TITLE
Add win percentage to career summary

### PR DESCRIPTION
**Pull request by randommonk**

### CODE REVIEW

**Comment by sn3p** [comment]
Nice @randommonk, still working on this on is this ready?

**Comment by randommonk** [comment]
It's ready!

**Comment by ThomasVdBerge** [comment]
Maybe also bump the version here: https://github.com/randommonk/utstats/blob/11dbc16efd459aeca1c19290f41924d2cc9eae0b/html/includes/footer.php

**Comment by sn3p** [comment]
Thanks, will do 👍

**Pull request merged**
