### PR TITLE
Added a bunch of new 900x300 map images.

### PR DESCRIPTION
**Pull request by davidbernard04**
Those are a few images from standard maps.

### CODE REVIEW

**Review by randommonk — APPROVED** [review]

**Comment by sn3p** [comment]
@davidbernard04 awesome! Also notice you deleted some images like `eternalcaves_large.jpg` and `eternalcave2_large.jpg`. Are they never used?

**Comment by davidbernard04** [comment]
@sn3p, well the map name is eternalcave, without a 's' or '2', so I cleaned them up!

I also replaced the original, because I hadn't realized at first it already had a map, but I found I prefered mine anyway. ;)

**Comment by sn3p** [comment]
> @sn3p, well the map name is eternalcave, without a 's' or '2', so I cleaned them up!

`eternalcave2` does exist 😜 

> https://nalicity.beyondunreal.com/map_hub.php?mid=619
> This is a remake of the original CTF-EnternalCave, more balanced, because of the identical bases (like red base in the original) which don't give any advantages to one of the teams (blue). I have first played in the sniper server, and it has great gameplay for multiplayer game!

I prefer to keep it in, all the others are fine and look great <3

**Comment by davidbernard04** [comment]
Lol indeed I should have thought of remakes. There might even be one with a 's'.. ;)

In any case I will revert at least the '2' one.

**Comment by davidbernard04** [comment]
@sn3p Done!

**Pull request merged**
